Traceback (most recent call last):
  File "c:\users\public\programs\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\public\programs\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\public\programs\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\public\programs\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\public\programs\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\public\programs\anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "c:\users\public\programs\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\public\programs\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
## load the file from local directory
#from google.colab import files
#uploaded = files.upload()

from google.colab import drive
drive.mount('/content/drive')

#drive.flush_and_unmount()
#print('All changes made in this colab session should now be visible in Drive.')

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_25640/2226028836.py[0m in [0;36m<module>[1;34m[0m
[0;32m      3[0m [1;31m#uploaded = files.upload()[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;33m[0m[0m
[1;32m----> 5[1;33m [1;32mfrom[0m [0mgoogle[0m[1;33m.[0m[0mcolab[0m [1;32mimport[0m [0mdrive[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      6[0m [0mdrive[0m[1;33m.[0m[0mmount[0m[1;33m([0m[1;34m'/content/drive'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      7[0m [1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'google.colab'
ModuleNotFoundError: No module named 'google.colab'

